{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "risf.serviceAccountName" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "risf.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: restricted-role
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "risf.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: restricted-role-binding
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "risf.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "risf.serviceAccountName" . }}
  namespace: {{ .Values.namespace.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: restricted-role
{{- end }}
