{{- if .Values.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "itsf.fullname" . }}-pvc
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "itsf.labels" . | nindent 4 }}
spec:
  storageClassName: ""
  accessModes:
  {{- range .Values.persistence.pvc.accessModes }}
    - {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.pvc.storage }}
{{- end }}
