apiVersion: v1
kind: Service
metadata:
  name: {{ include "itsf.fullname" . }}-service
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "itsf.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "itsf.selectorLabels" . | nindent 4 }}
