apiVersion: v1
kind: ServiceAccount
metadata:
  name: restricted-service-account
  namespace: itsf
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: minimal-permissions
  namespace: itsf
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: restricted-binding
  namespace: itsf
subjects:
- kind: ServiceAccount
  name: restricted-service-account
  namespace: itsf
roleRef:
  kind: Role
  name: minimal-permissions
  apiGroup: rbac.authorization.k8s.io
