apiVersion: v1
kind: PersistentVolume
metadata:
  name: itsf-pv
spec:
  storageClassName: ""
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /run/desktop/mnt/host/c/Users/mhali/Desktop/Dev/technical_tests/itsf/pv
    type: Directory
