apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: itsf
type: kubernetes.io/tls
data:
  # Les valeurs seront remplacées par les certificats encodés en base64
  # Après avoir exécuté le script create-pki.sh, utilisez:
  # cat certs/tls.crt | base64 -w 0
  # cat certs/tls.key | base64 -w 0
  tls.crt: ""
  tls.key: ""
