# Default values for ITSF chart
replicaCount: 1

image:
  repository: itsf
  tag: latest
  pullPolicy: Never

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: hello-itsf.local.domain
      paths:
        - path: /
          pathType: Prefix
    - host: www.hello-itsf.local.domain
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: tls-secret-hello-itsf-local-domain
      hosts:
        - hello-itsf.local.domain
        - www.hello-itsf.local.domain

serviceAccount:
  create: true
  name: "restricted-service-account"

resources:
  limits:
    cpu: 0.5
    memory: 512Mi
  requests:
    cpu: 0.2
    memory: 256Mi

securityContext:
  runAsNonRoot: true
  runAsUser: 1001
  runAsGroup: 1001
  fsGroup: 1001

containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1001

persistence:
  enabled: true
  pvc:
    accessModes:
      - ReadOnlyMany
    storage: 50Mi

namespace:
  name: itsf
  create: true
