# Ce workflow a été intégré directement dans standard.yml
# Ce fichier est conservé pour référence mais n'est plus utilisé

name: Kubernetes Validation

on:
  push:
    paths:
      - "itsf/k8s/**"
      - "risf/k8s/**"
      - ".github/workflows/kubernetes.yml"
  pull_request:
    paths:
      - "itsf/k8s/**"
      - "risf/k8s/**"
      - ".github/workflows/kubernetes.yml"
  workflow_dispatch: # Permet de déclencher manuellement le workflow

jobs:
  validate-kubernetes:
    name: Valider les manifests Kubernetes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Installer Kubeval
        run: |
          curl -L -o kubeval.tar.gz https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz
          tar -xzf kubeval.tar.gz
          sudo mv kubeval /usr/local/bin/
          rm kubeval.tar.gz

      - name: Valider avec Kubeval
        run: |
          for dir in "itsf/k8s/" "risf/k8s/"; do
            echo "Validation du répertoire ${dir} avec Kubeval"
            kubeval --ignore-missing-schemas ${dir}*.yaml
          done
